name: release-to-maven-central
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Will start a Maven Central upload with version ${{ github.event.inputs.releaseversion }}"

      - uses: actions/checkout@v3

      - name: Set up settings.xml for Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set up Git user
        run: |
          git config --global user.name "Neolegal (body) Builder"
          git config --global user.email "build@neolegal.fr"

      - name: Publish package
        run: |
          mvn --batch-mode clean versions:set -DremoveSnapshot
          mvn --batch-mode deploy --no-transfer-progress -P central-deploy -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: commit version increment
        run: |
          git add pom.xml
          git commit -m "Update versions in pom.xml after release"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ github.token }}